### ISSUE TITLE
Incorrect paths in .pre-commit-config.yaml skip out on tests.

### ISSUE THREAD

**Issue by jenstroeger** [jenstroeger/python-package-template#38]
A regression introduced with PR https://github.com/jenstroeger/python-package-template/pull/27: the git hooks didn’t run their tests over the package source anymore because the source’s moved into the `src/` folder.

For example,

https://github.com/jenstroeger/python-package-template/blob/eaa6a604e739e1667ae390dc69cafa576dea597e/.pre-commit-config.yaml#L40-L42

uses a [regex for the `files` entry](https://pre-commit.com/#regular-expressions) and matches that regex against path names. That regex wouldn’t match anymore for the new `src/package/…` paths and therefore files wouldn’t be picked for the hook anymore. Not sure that’s actually fixable on the [pre-commit](https://github.com/pre-commit/pre-commit) side because the matched list of files is not empty — it’s just not complete either 🤔

I also noticed that [mypy](https://github.com/python/mypy) would generate an error
```
tests/test_something.py:5:1: error: Skipping analyzing "package.something": found module but no type hints or library stubs
tests/test_something.py:5:1: note: See https://mypy.readthedocs.io/en/stable/running_mypy.html#missing-imports
Found 1 error in 1 file (checked 2 source files)
```
which can be fixed by adding [mypy_path](https://mypy.readthedocs.io/en/stable/config_file.html#confval-mypy_path) to the configuration.
